### ISSUE TITLE
[bug] Cannot view full value of collapsed headers

### ISSUE THREAD

**Issue by reporter29** [httptoolkit/httptoolkit-ui#123]
Using windows 10 and the free version of HTTP Toolkit. Can't seem to find the version I'm using but I believe it's the latest.

The button below is not responsive. I click it and nothing happens. Seems to be related to [#746](https://github.com/httptoolkit/httptoolkit-ui/commit/612d639aea70aafc3115e6f5c294af43841d9508).

![image](https://github.com/user-attachments/assets/deddb8d2-8ac2-4534-a54a-e66dc01c6871)

**Comment by pimterry** [comment]
You can click the + on the left to expand the row and it'll show the full content.

I've heard a couple of mentions that this is confusing though so I'll look at tweaking that. The ... was just intended as a marker rather than a button, but it definitely could become one instead.

**Comment by reporter29** [comment]
> You can click the + on the left to expand the row and it'll show the full content.

This works.

> I've heard a couple of mentions that this is confusing though so I'll look at tweaking that. The ... was just intended as a marker rather than a button, but it definitely could become one instead.

It's definitely confusing. If you wanted to still use the + on the left to keep things consistent, perhaps making the ... trail after the collapsed text without any gray background would make it more clear that it isn't a button.

**Comment by pimterry** [comment]
I've just changed this so that the ... icon now is indeed a button as you (and a couple of other people) originally expected. After the text is expanded, that now becomes a little minus button, to collapse the header again. I've also increased what's considered a "large" header, so we can avoid a few cases where this appeared unnecessarily.

On a related note, I've also just added a context menu to the headers, so you can right click headers anywhere and directly copy the name, value, or "name: value" as a string without needing to select the header content manually (and without needing to expand large headers like these).

Hopefully that'll all now work nicely for you but do let me know if you have any other feedback.
