### ISSUE TITLE
ingest.us.sentry.io

### ISSUE THREAD

**Issue by adamoutler** [httptoolkit/httptoolkit-ui#141]
Whenever I click on items in the UI, it makes 2 requests to https://o202389.ingest.us.sentry.io/api/1316304/envelope/ .

![image](https://github.com/user-attachments/assets/ccab5bf3-8425-4b4b-9bf3-7e215eaa7d75)

I don't see a way to stop it or opt-out and my email address is being shared.

To reproduce:
1. Start HTTP Toolkit
2. Intercept the same machine running HTTP Toolkit
3. Observe each click within the UI introduces two new requests.

This makes for noisy logs, and I question the motives.

**Comment by pimterry** [comment]
Hi @adamoutler - this is used for error tracking with [Sentry](https://sentry.io), an error monitoring tool very widely used in all sorts of software. If you're interested in knowing more about how your data might be stored or processed, there's details in HTTP Toolkit's privacy policy here: https://httptoolkit.com/privacy-policy/.

Sentry's monitoring is generally anonymous for free users, and Sentry includes features which scrub private data such as IP or any other sensitive fields for all users so that's never stored or processed. Request & response content isn't sent here either, just basic UI events (e.g. button X clicked, checkout opened, request to HTTP Toolkit API failed). For Pro users only, the account email is also included, as this is often important to contact & directly support paying users who are having specific issues, especially problems during the checkout process itself, and it's already data we need to collect and process for basic account management regardless (e.g. login, sending invoices, etc).

No Sentry data is ever used for any kind of marketing, tracking or behaviour monitoring, on either an aggregate or individual level. Sentry requests are exclusively capturing context of recent events, so that if a notable error occurs that context can be included with this (to be honest, I'm surprised that it's not cached locally until an error happens, but that's a detail of the Sentry SDK - I'll look into it). All Sentry data is deleted after 90 days regardless, it's never exported or shared elsewhere, or processed for any purpose but error monitoring, and all Sentry's privacy & data scrubbing features are enabled to limit any further risks here if personal data was somehow collected.

In practice, error reports in Sentry look like "A windows user clicked a request row, selected 'Curl' export format, and an exception thrown with '...'". Error tracking like this is absolutely essential for catching and debugging specific issues, and has already caught a lot of problems and very significantly improved HTTP Toolkit overall.

I'm sensitive to concerns about privacy here, and how those can be balanced against the need for software error monitoring, and suggestions are welcome. Is there a specific scenario or risk to your data that you're worried about here?

**Comment by adamoutler** [comment]
I just see an email and a hash being sent twice, each time I click something.  The privacy concerns are obvious and it seems like it would be more fitting for a "Debug Mode".

**Comment by pimterry** [comment]
> I just see an email and a hash being sent twice, each time I click something. 

This is now fixed - I agree this was a bit wasteful & noisy, thanks for pointing that out.

That was due to a new default-on feature for overall session health monitoring in a Sentry release HTTP Toolkit updated to recently (see https://forum.sentry.io/t/understanding-the-events-sent-by-the-js-sdk-type-session/13606/3 for more details). It's designed to check the percentage of 'sessions' where a crash occurs, per release, so you can spot broken releases, but tracking sessions automatically on a per-URL basis means this isn't actually very helpful for HTTP Toolkit anyway. The app will update in the background next time you launch it - this fix will take effect the following launch and you won't see this any more.

There are still occasional Sentry requests elsewhere though, particularly when an actual error happens - it's just that I've just disabled the session tracking that resulted in much more frequent requests.

> The privacy concerns are obvious

Happy to discuss them if you'd like, but it would be helpful if you can be specific about your concerns. It's difficult to discuss privacy & tradeoffs without a concrete threat model, to define the potential scenarios & risks that you're worried about.

In this case, the data being sent here is only available to me personally (and I already have the email, latest IP, and assorted subscription & payment data etc for every Pro customer anyway, as part of account management) and Sentry. Sentry are a large & reliable error monitoring provider, and although they are a 3rd party they're widely trusted, and they're publicly committed to protecting this data, deleting it after 90 days, and acting as a data processor for error monitoring only here. It's not clear how it would be in their interest to abuse that or how they could abuse the minimal information here.

On my side, this data isn't being used for marketing or tracking in any sense, and other than the email address & your IP, the data itself is neither personal data (in the strict GDPR sense) nor particularly sensitive (imo - there's no actual HTTP data here, just "clicked button X" kinds of events). What you're sending or receiving, or how you're using any of the intercepted targets is _not_ recorded, as that clearly could be problematic and expose important data.

> it seems like it would be more fitting for a "Debug Mode".

This isn't practical unfortunately. Software needs active monitoring of production environments. Many issues are intermittent, or just don't get reported at all (99% of users will hit a major issue and just disappear without reporting it). The goal of error monitoring in this case is to generally to make sure HTTP Toolkit keeps working, spot real-world issues early when they appear (particularly after new releases) and especially detect breakages in the _many_ 3rd party integrations (this is common! E.g. a new Firefox release might break the interception mechanism, causing a spike of new error reports). It would be practically impossible for me to single-handled maintain the depth & breadth of integrations in HTTP Toolkit without this. Being able to on-demand enable a debug mode doesn't solve this primary use case.

This is common elsewhere - likely every service you use monitors significantly more than HTTP Toolkit does. Sentry's other customers actually include GitHub, and I can see a whole series of request to collector.github.com/github/collect on this very page, doing this same behaviour: tracking a session for every URL change, and including your GitHub username with it (and lots more!).

Sentry is also used by Microsoft, Cloudflare, Slack, Atlassian... If you're using any modern serious software, there will be error monitoring in place doing this or something very similar. This is not the same as product user analytics or ad tracking, which are distinct technologies that track very different data (much more granular & personal data to understand individual's behaviours) for very different purposes.

I agree that there's a temptation for abuse to use this, e.g. to profile users for advertising or direct marketing, or even sell this data, etc etc, but at least in HTTP Toolkit's case I can assure you that that's not happening - even if I wanted to, frankly I literally don't have time :smile:. And of course, it's all open source, so you can directly examine this for yourself if you'd like, or even maintain your own fork with sentry disabled if you prefer. The UI logic for this starts [here](https://github.com/httptoolkit/httptoolkit-ui/blob/main/src/errors.ts), which configures it to auto-track all uncaught exceptions, and you can also see explicit calls to track errors by searching for that `logError` method elsewhere.

**Comment by adamoutler** [comment]
At a minimum this does not comply with European GDPR. You must obtain consent before transmitting and storing a user's email in logs. Eg chatgpt explanation https://chatgpt.com/share/67226774-2ecc-8011-ab81-c24970bd6dfe

However keeping in mind that the overlap between security-concsious users and privacy-conscious users is large, and people who use your tool are likely highly security conscious, this does not follow good security practice in general.  If someone is MITM my traffic they will see this tool I expect to be listening, also transmitting it's own data and it can be seen what they are doing.  Additionally based on DNS and routing requests you can know what app is being used, and due to the frequency of requests, you can infer how long and when it was used by nothing but network traffic. 

I think disabling the "extras" is a good first step, but it should be opt-in or at least opt-out buried in some menu.

**Comment by pimterry** [comment]
> At a minimum this does not comply with European GDPR. You must obtain consent before transmitting and storing a user's email in logs. Eg chatgpt explanation https://chatgpt.com/share/67226774-2ecc-8011-ab81-c24970bd6dfe

I'm based in the EU, I've filed GDPR reports myself (here's some examples, relating to specific concerns like data sharing for cross-site ad tracking: https://x.com/pimterry/status/1192028773526441985, and email scraping & profiling for recruitment: https://x.com/pimterry/status/1068453441536692225) and I have a reasonably good understanding of the legalities here. I should note that I have taken legal advice around this generally, and HTTP Toolkit has been through security auditing by 3rd party security teams too. It is fully GDPR compliant, for EU users and for everybody else worldwide too (and I would not recommend ChatGPT for legal advice).

In this case, 'Legitimate interest' is a lawful basis for processing under GDPR that doesn't require consent, as long as the privacy impact is minimal (e.g. collecting the email address that I already necessarily have anyway), where it's 'reasonably necessary' processing to run the business, and where you take reasonable efforts to balance business interests vs individual privacy (i.e. not tracking any unnecessary or private data, very limited retention, very limited purposes, etc). Marketing is widely accepted as not 'necessary', but monitoring errors in production is well within the definition of necessary and perfectly normal business functions.

https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/a-guide-to-lawful-basis/lawful-basis-for-processing/legitimate-interests/ has a good background if you're interested in digging into this further. Again, this is different from user analytics, tracking & profiling which _does_ require user consent if any private data is collected or processed.

Your chatgpt log touches on this: '...logging email addresses without user consent could violate GDPR **unless it's justifiable under legitimate interests**'. It also repeatedly mentions that this should be communicated in the [privacy policy](https://httptoolkit.com/privacy-policy/) (which it is).

You'll note as well from my comment above that GitHub also tracks session error data in the same ways with far wider scope (and I'm sure has had a lot more legal help to ensure this is OK than I have) with no opt-out. They are one example of millions - almost all modern software does something similar. It's very hard to know how software is going wrong in production (annoyingly) so you need to monitor it! Is there a difference between their stance & HTTP Toolkit's that affects your concerns here?

> If someone is MITM my traffic they will see this tool I expect to be listening, also transmitting it's own data and it can be seen what they are doing.

If your application traffic is MitM it's already game over I'm afraid. For starters, because they can actually see the all the traffic you're intercepting with HTTP Toolkit (not just that you're using it briefly: they can see who you're talking to with it, for how long, and everything you're saying). Also, for Pro users, HTTP Toolkit has to talk to its account servers at a reasonable interval anyway, so if you're MitM'd then your current account status & user info is exposed anyway even without sentry. HTTP Toolkit also checks for app updates every 10 minutes or so.

Meanwhile, now that the original issue here is fixed, our error monitoring sends requests only intermittently when you hit uncaught exceptions, so there's not much interesting info that can be derived there at all. In terms of DNS & routing metadata, in the moments where intermittent requests do fire, all you can see is that a Sentry-using software is being used (but again - that's true for 100s of thousands of different products, so this doesn't actually tell anybody you're using HTTP Toolkit specifically).

In practice, if somebody malicious can MitM your traffic then you're in _much_ more trouble than just leaking your email, and error monitoring is adding no discernable risk to this that I can see.

To wrap up, I think error monitoring is very useful, justifiable, provides huge benefits with little downside, and is very much normal in modern software, and so I'm very keen not to lose that. That said, I'm definitely open to discussion and tweaking of specific details here. For example, what do you think about changing the Sentry user context to use a user id (a random string unique to each user) instead of the email? That would be enough for me to find affected Pro users if required when things crash, but would ensure that Sentry themselves or anybody else viewing that specific traffic doesn't actually know who the user is (because they don't have any access to the user accounts database). Is your main concern that the email itself is directly exposed? If so, this could resolve that.

Regardless, in the meantime I can see you're not super happy about this, and that you're a Pro user who's affected. There's two practical immediate solutions available if you'd like:

* You can fork the UI (or the whole project) and self-host it without any tracking. There's info for this in the UI README: https://github.com/httptoolkit/httptoolkit-ui/#readme
* Or, if you'd prefer, I'm happy to just refund and close your Pro account instead - just let me know. If you're using the tool without logging in then the same error reports are sent when things break, but no email or user data is included.

**Comment by adamoutler** [comment]
You're keying into the MITM part.  The rest of it was more worrisome because it doesn't take anything except eves dropping.  

I see your privacy policy is updated.  I was looking earlier at the privacy policy on your site and saw it collected name and account number.  A quick search now shows email mentioned.

**Comment by pimterry** [comment]
> You're keying into the MITM part. The rest of it was more worrisome because it doesn't take anything except eves dropping.

I'm not sure what you mean. How do you eavesdrop without a MitM on the connection? 

Given the explanation above, can you explain which bit is still worrisome and why? In all scenarios I'm aware of, any attacker who can somehow see the contents of these Sentry requests can also see plenty of other requests (the update checks & account data API calls) that expose the same amount or more information about the software you're using and when (and this attacker would also have a lot of other larger potential options to cause damage or access your data from such a position anyway). Disabling the sentry reports for errors doesn't make a difference.

Does that make sense?

> I see your privacy policy is updated

Depends when you checked it, but generally the privacy policy hasn't changed for quite a bit, if you're interested the raw source (and full history) is available here: https://github.com/httptoolkit/httptoolkit-website/blob/main/src/app/(legal)/privacy-policy/content.mdx

Do let me know if you have any thoughts on the potential improvement, or other 2 alternative resolutions at the end of my last message.

**Comment by adamoutler** [comment]
> I'm not sure what you mean. How do you eavesdrop without a MitM on the connection?

There are ways to monitor activity without decryption if you're on the same network.

1. Standard plain-text DNS traffic - shows what websites are being used.
2. Standard encrypted TCP packet, plain-text IP headers - shows when an IP is accessed.  
3. Inference of above shows for how long you're using an app/site.

**Comment by pimterry** [comment]
I don't think any of that data expose any meaningful information in this scenario. Sentry is used by _many_ products (100s of thousands) so seeing their IP & domain name in network traffic doesn't tell you anything about the product a user is using locally. And with the latest changes, HTTP Toolkit does not frequently send Sentry requests as you use the tool so there is no stream of requests to monitor.

Lastly, as in my previous comment: Sentry requests don't matter anyway because there are many other necessary requests (checking subscription status & checking for app updates) that _are_ sent at frequent intervals and do uniquely identify HTTP Toolkit traffic (e.g. requests to the accounts.httptoolkit.tech API) so if you can see network metadata then you can already detect HTTP Toolkit usage regardless. Those requests are necessary for essential functionality, since the tool needs to know if you create a subscription or cancel etc, and needs to receive updates effectively.

I'm going to close this issue now. Thanks for reporting the initial issue here about sending requests per-click, that was definitely suboptimal and it's great to have that now resolved. If there's another case where there are specific concerns, or if you run into more issues then do please let me know, but given the need for connectivity for app updates & account data, I don't think the existence of Sentry here is meaningfully impacting user privacy right now.
