### ISSUE TITLE
404 when launching http://local.httptoolkit.tech:8080/

### ISSUE THREAD

**Issue by Surasia** [httptoolkit/httptoolkit-ui#88]
I'm getting a 404 not found error, where the main webpack output should be. http://local.httptoolkit.tech:8080/index.html displays the monitorix window, however the main UI is not shown. I've cleared any caches I have, launched completely new browsers yet the issue persists.

I'm using Linux Mint 20.1 with the latest LTS version of NodeJS.

![resim](https://github.com/httptoolkit/httptoolkit-ui/assets/74399067/7ce2ded8-80b1-4a1c-8709-8f7746fc8aa0)

**Comment by pimterry** [comment]
Hi @Surasia, I'm not sure what's going on here - that Monitorix page is not coming from HTTP Toolkit though, HTTP Toolkit doesn't use Monitorix anywhere, so this must be something coming from elsewhere.

I suspect this means that the UI server has not started on port 8080, because Monitorix is already using it. If you take a look at the console output from `npm start`, you may be able to see more information there - it may be that startup has failed, or another port has been selected automatically instead.

**Comment by Surasia** [comment]
Oh I just noticed that I had Monitorix running in the background using the 8080 port.... sometimes I should check more before opening a github issue
